language: python
cache: pip
sudo: false
python:
- '3.6'
- '3.5'
- '2.7'
env:
- REQ="https://github.com/django/django/archive/master.zip#egg=Django"
- REQ="Django>=2.1,<2.2"
- REQ="Django>=2.0,<2.1"
- REQ="Django>=1.11,<2.0"
matrix:
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
  exclude:
    - python: '2.7'
      env: REQ="Django>=2.1,<2.2"
    - python: '2.7'
      env: REQ="Django>=2.0,<2.1"
    - python: '2.7'
      env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
install:
- pip install -U pip wheel
- pip install $REQ pytz
- python setup.py install
script: cd tests && ./manage.py test -v 2 testapp && cd ..

jobs:
  include:
    - stage: style
      env: REQ=none
      install: skip
      script:
        - pip install black flake8
        - flake8 .
        - black --check user_messages tests
